name: Construir Plugin (Solo Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 1. Clonar Repositorio
      uses: actions/checkout@v4

    - name: 2. Configurar CMake
      run: cmake . -B Builds -D VST2_SDK_PATH="vst2sdk"

    - name: 3. Construir el Plugin con CMake
      run: cmake --build Builds --config Release

    - name: 4. Preparar Paquete de Artefactos
      id: package
      shell: bash
      run: |
        PLUGIN_NAME="DynamicRangeSentinel"
        PACKAGE_DIR="dist"
        mkdir -p $PACKAGE_DIR

        # Encontrar y mover VST3
        VST3_PATH=$(find Builds -name "${PLUGIN_NAME}.vst3" -print -quit)
        if [ -n "$VST3_PATH" ]; then
          mv "$VST3_PATH" "$PACKAGE_DIR/"
        fi
        
        # Encontrar y mover VST2
        VST2_PATH=$(find Builds -path "*Release/${PLUGIN_NAME}.dll" -print -quit)
        if [ -n "$VST2_PATH" ]; then
          mv "$VST2_PATH" "$PACKAGE_DIR/"
        fi
        
        # Comprimir los artefactos encontrados
        ZIP_NAME="${PLUGIN_NAME}-VST-Bundle-Win.zip"
        cd $PACKAGE_DIR && zip -r ../$ZIP_NAME . && cd ..
        echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT

    - name: 5. Subir el Artefacto Comprimido
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.package.outputs.zip_name }}
        path: ${{ steps.package.outputs.zip_name }}
