name: Build VST2 for Windows & Linux

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout project code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          # Versión de webkitgtk ajustada a la 4.0, que es la que busca CMake
          sudo apt-get install -y libasound2-dev libjack-jackd2-dev libfreetype6-dev libx11-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libwebkit2gtk-4.0-dev libgtk-3-dev

      - name: Build
        id: build
        shell: bash 
        run: |
          cmake -B Builds
          cmake --build Builds --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DynamicRangeSentinel-${{ runner.os }}
          path: Builds/DynamicRangeSentinel_artefacts/Release/
