name: Build VST2 for Windows & Linux

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        # Matriz de compilación para nuestros objetivos de MVP
        os: [windows-latest, ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      # Paso 1: Descargar el código fuente.
      - name: Checkout project code
        uses: actions/checkout@v4

      # Paso 2: Instalar dependencias de Linux.
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          # Paquete 'libgtk-3-dev' añadido para las dependencias de la GUI
          sudo apt-get install -y libasound2-dev libjack-jackd2-dev libfreetype6-dev libx11-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libwebkitgtk-6.0-dev libgtk-3-dev

      # Paso 3: Compilación
      - name: Build
        id: build
        # Forzar el uso de Bash en todos los sistemas.
        shell: bash 
        run: |
          # Comando de configuración estándar.
          cmake -B Builds
          cmake --build Builds --config Release

      # Paso 4: Carga de los artefactos (instaladores)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DynamicRangeSentinel-${{ runner.os }}
          path: Builds/DynamicRangeSentinel_artefacts/Release/
