name: Build DynamicRangeSentinel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.22.0"

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libx11-dev libfreetype6-dev libxrandr-dev libxinerama-dev libxcursor-dev libxext-dev mesa-common-dev

      - name: Create Build Directory
        run: cmake -E make_directory ${{github.workspace}}/Builds

      - name: Configure CMake
        run: |
          cmake -B Builds -DCMAKE_BUILD_TYPE=Release
        shell: bash

      - name: Build
        run: cmake --build Builds --config Release
