name: Build JUCE Project

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4

      # --- Dependencias para Linux ---
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libjack-jackd2-dev libfreetype6-dev libx11-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libwebkit2gtk-4.0-dev

      # --- Clonar VST2 SDK (Solo para macOS, donde es requerido) ---
      - name: Clone VST2 SDK
        if: runner.os == 'macOS'
        run: git clone https://github.com/steinbergmedia/vst2sdk.git ../vst2sdk

      # --- Compilación ---
      - name: Build
        id: build
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            # Pasa la ruta del VST2 SDK a CMake en macOS
            cmake -B Builds -DJUCE_VST2_SDK_PATH=../vst2sdk
          else
            # Comando CMake estándar para Windows y Linux
            cmake -B Builds
          fi
          cmake --build Builds --config Release

      # --- Carga de Artefactos ---
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DynamicRangeSentinel-${{ runner.os }}
          path: |
            Builds/DynamicRangeSentinel_artefacts/Release/
