name: Construir y Publicar Plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: 1. Clonar Repositorio
      uses: actions/checkout@v4

    - name: 2. Instalar Dependencias (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config gobjc++ libasound2-dev libjack-jackd2-dev libx11-dev libxinerama-dev libxrandr-dev libxcursor-dev libgl-dev libfreetype6-dev libfontconfig1-dev libgtk-3-dev

    - name: 3. Construir el Plugin con CMake
      run: |
        cmake . -B Builds
        cmake --build Builds --config Release
    
    - name: 4. Subir el Artefacto
      uses: actions/upload-artifact@v4
      with:
        name: DRS-Build-${{ matrix.os }}
        path: Builds/DynamicRangeSentinel_artefacts/Release/VST/
