name: Construir y Publicar Plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # LA SOLUCIÓN: Hemos eliminado 'ubuntu-latest' de la lista.
        os: [windows-latest, macos-latest]

    steps:
    - name: 1. Clonar Repositorio
      uses: actions/checkout@v4

    # El paso de dependencias de Linux ya no es necesario.

    - name: 2. Construir el Plugin con CMake
      run: |
        cmake . -B Builds
        cmake --build Builds --config Release
    
    - name: 3. Subir el Artefacto
      uses: actions/upload-artifact@v4
      with:
        name: DRS-Build-${{ matrix.os }}
        path: Builds/DynamicRangeSentinel_artefacts/Release/VST/
