name: Construir y Publicar Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    # El SDK ahora se clona como parte del repositorio principal.
    - name: 1. Clonar Repositorio
      uses: actions/checkout@v4

    - name: 2. Instalar Dependencias (Linux)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config gobjc++ libasound2-dev libjack-jackd2-dev libx11-dev libxinerama-dev libxrandr-dev libxcursor-dev libgl-dev libfreetype6-dev

    - name: 3. Configurar CMake
      shell: bash
      run: |
        # La ruta al SDK sigue siendo válida, ahora es un directorio local.
        SDK_PATH="vst2sdk"
        if [ "${{ matrix.os }}" == "macos-latest" ]; then
          cmake . -B Builds -D VST2_SDK_PATH=$SDK_PATH -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
        else
          cmake . -B Builds -D VST2_SDK_PATH=$SDK_PATH
        fi

    - name: 4. Construir el Plugin con CMake
      run: cmake --build Builds --config Release

    - name: 5. Preparar Paquete de Compatibilidad Total
      # ... (Esta sección no cambia y permanece como en la versión anterior) ...
